//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDS_New.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double SELF_RADIUS {
            get {
                return ((double)(this["SELF_RADIUS"]));
            }
            set {
                this["SELF_RADIUS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double DETECTOR_RADIUS {
            get {
                return ((double)(this["DETECTOR_RADIUS"]));
            }
            set {
                this["DETECTOR_RADIUS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1E-35")]
        public double AFF_SCALE {
            get {
                return ((double)(this["AFF_SCALE"]));
            }
            set {
                this["AFF_SCALE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double CHOOSEN_COEFF {
            get {
                return ((double)(this["CHOOSEN_COEFF"]));
            }
            set {
                this["CHOOSEN_COEFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double CLONAL_COEFF {
            get {
                return ((double)(this["CLONAL_COEFF"]));
            }
            set {
                this["CLONAL_COEFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5,0.5, 0.5, 0.5, 0.5, 0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0" +
            ".5,0.5,0.5,0.5,0.5")]
        public string WEIGHTS {
            get {
                return ((string)(this["WEIGHTS"]));
            }
            set {
                this["WEIGHTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VIRUS_CODE {
            get {
                return ((int)(this["VIRUS_CODE"]));
            }
            set {
                this["VIRUS_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BENIGN_CODE {
            get {
                return ((int)(this["BENIGN_CODE"]));
            }
            set {
                this["BENIGN_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int BASIC_FEATURES {
            get {
                return ((int)(this["BASIC_FEATURES"]));
            }
            set {
                this["BASIC_FEATURES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double DLLS_MUTATION {
            get {
                return ((double)(this["DLLS_MUTATION"]));
            }
            set {
                this["DLLS_MUTATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3,0.3, 0.3, 0.3, 0.3, 0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0" +
            ".3,0.3,0.3,0.3,0.3")]
        public string STRATEGY_PARAS {
            get {
                return ((string)(this["STRATEGY_PARAS"]));
            }
            set {
                this["STRATEGY_PARAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Input.txt")]
        public string INPUT_TXT_PATH {
            get {
                return ((string)(this["INPUT_TXT_PATH"]));
            }
            set {
                this["INPUT_TXT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TIME_LOOP {
            get {
                return ((int)(this["TIME_LOOP"]));
            }
            set {
                this["TIME_LOOP"] = value;
            }
        }
    }
}
